blueprint:
  name: NFC-Tag Sonos Steuerung
  description: >
    # 💡 NFC-Tag plays Music
    **Version: 0.1**
    With this blueprint, you can select which music should be played when an NFC tag is scanned. ✨
    **If you like my blueprints and would like to show your support or just say thank you,** [Click Here](https://www.paypal.com/donate/?hosted_button_id=Y33CF7RUEEFF4). Thank you!
    <details>
    <summary><b>The Automation Process:</b> 👈</summary>
      - **Prerequisites:**
        - *Create a new helper [input_text] `input_text.last_scanned_tag` ("Last scanned Tag", Value: max. 100 chars)
        - *Create a new helper [counter] `counter.last_radio_index` ("Last Played Radio Index", Value: e.g. 0-4, depending on how many radios you want)
      - **Trigger:**
        - You can choose any NFC tag registered in Home Assistant to trigger the automation.
      - **Configuration:**
        - You can select a Spotify playlist or use the Home Assistant integrated RadioBrowser.
    </details>
  domain: automation
  input:
    tag_id:
      name: NFC-Tag ID
      description: "The ID of the NFC tag that triggers this automation."
      selector:
        entity:
          domain: tag

    media_player:
      name: Speakers
      description: "The speakers to be controlled. You can select multiple."
      selector:
        entity:
          domain: media_player
          multiple: true

    media_content_id:
      name: Media content
      description: "The Spotify playlist or the radio station to be played."
      selector:
        text:

    media_content_type:
      name: Media content type
      description: "Type of content to be played."
      selector:
        select:
          options:
            - label: "Spotify"
              value: "spotify"
            - label: "Internet-Radio"
              value: "music"

    is_radio:
      name: More than one Radio station?
      description: "If activated, the system switches through a channel list. (Only relevant if 'Internet-Radio' is selected)"
      default: false
      selector:
        boolean:

    stations:
      name: Radio station list
      description: "List of radio stream URLs (Only relevant if 'Internet-Radio' is selected and multiple stations are desired)."
      default: []
      selector:
        object:
